import { UnitDetail } from "@/types/Units";

export const unitDetailMap: Record<number, UnitDetail> = {
  1: { id: 1, name: "Kilo Gram", symbol: "Kg", noOfDecPlaces: 3 },
  2: { id: 2, name: "Piece", symbol: "Pcs", noOfDecPlaces: 0 },
  3: { id: 3, name: "Centimetre", symbol: "cms", noOfDecPlaces: 3 },
  4: { id: 4, name: "Cubic CentiMetre", symbol: "cm3", noOfDecPlaces: 3 },
  5: { id: 5, name: "Gram", symbol: "gms", noOfDecPlaces: 3 },
  6: { id: 6, name: "Kilolitre", symbol: "Kl", noOfDecPlaces: 3 },
  7: { id: 7, name: "Litre", symbol: "Ltr", noOfDecPlaces: 3 },
  8: { id: 8, name: "Thousand in number", symbol: "Thu", noOfDecPlaces: 3 },
  9: { id: 9, name: "Metre", symbol: "mtr", noOfDecPlaces: 2 },
  10: { id: 10, name: "Square Metre", symbol: "mt2", noOfDecPlaces: 3 },
  11: { id: 11, name: "Millimetre", symbol: "mm", noOfDecPlaces: 3 },
  12: { id: 12, name: "Metric Tonne", symbol: "MT", noOfDecPlaces: 3 },
  13: { id: 13, name: "Number of Pairs", symbol: "Pa", noOfDecPlaces: 0 },
  14: { id: 14, name: "Tonne", symbol: "Ton", noOfDecPlaces: 3 },
  15: { id: 15, name: "Quintal", symbol: "Qtl", noOfDecPlaces: 3 },
  16: { id: 16, name: "Number", symbol: "Num", noOfDecPlaces: 0 },
  18: { id: 18, name: "hectares", symbol: "ha", noOfDecPlaces: 4 },
  19: { id: 19, name: "Decimeters", symbol: "dm", noOfDecPlaces: 2 },
  20: { id: 20, name: "acres", symbol: "Acr", noOfDecPlaces: 2 },
  21: { id: 21, name: "Service", symbol: "", noOfDecPlaces: 3 },
  22: { id: 22, name: "Dozen", symbol: "Dz", noOfDecPlaces: 2 },
  23: { id: 23, name: "gross", symbol: "gr", noOfDecPlaces: 1 },
  24: { id: 24, name: "Box", symbol: "box", noOfDecPlaces: 0 },
  25: { id: 25, name: "Caret", symbol: "Crt", noOfDecPlaces: 2 },
  26: { id: 26, name: "Running Feet", symbol: "RFt", noOfDecPlaces: 2 },
  27: { id: 27, name: "Square Feet", symbol: "SFt", noOfDecPlaces: 2 },
  28: { id: 28, name: "Cubic Feet", symbol: "CFt", noOfDecPlaces: 2 },
  29: { id: 29, name: "Set", symbol: "set", noOfDecPlaces: 1 },
  30: { id: 30, name: "Kit", symbol: "kit", noOfDecPlaces: 1 },
  31: { id: 31, name: "Bags", symbol: "bag", noOfDecPlaces: 1 },
  34: { id: 34, name: "Inches", symbol: "in", noOfDecPlaces: 2 },
  35: { id: 35, name: "Milliletre", symbol: "ml", noOfDecPlaces: 3 },
  36: { id: 36, name: "Milligram", symbol: "mg", noOfDecPlaces: 3 },
  37: { id: 37, name: "ROLLS", symbol: "ROL", noOfDecPlaces: 0 },
  119: { id: 119, name: "Yards", symbol: "yds", noOfDecPlaces: 3 },
  120: { id: 120, name: "Packets", symbol: "pkt", noOfDecPlaces: 0 },
};
